### ISSUE TITLE
Cannot connect to Sonarr API in v4.x

### ISSUE THREAD

**Issue by ghost** [ryakel/sonarr-yt-dlp#30]
Looks like this was broken with the update to Sonarr 4.0 that just released.

2024-01-02 10:24:59,878 - sonarr_youtubedl - INFO - Initial run
2024-01-02 10:24:59,878 - sonarr_youtubedl - INFO - Configuration Found. Loading file.
2024-01-02 10:24:59,881 - sonarr_youtubedl - INFO - Scan interval set to every 30 minutes by config.yml
2024-01-02 10:24:59,881 - sonarr_youtubedl - DEBUG - DEBUGGING ENABLED
2024-01-02 10:24:59,882 - sonarr_youtubedl - DEBUG - Begin call Sonarr for all available series
2024-01-02 10:24:59,882 - sonarr_youtubedl - DEBUG - Begin GET with url: http://192.168.86.251:8989/api/series
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/sonarr_youtubedl.py", line 440, in <module>
    main()
  File "/app/sonarr_youtubedl.py", line 432, in main
    series = client.filterseries()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/sonarr_youtubedl.py", line 182, in filterseries
    series = self.get_series()
             ^^^^^^^^^^^^^^^^^
  File "/app/sonarr_youtubedl.py", line 118, in get_series
    return res.json()
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Two potential reasons for this from the changelog:

* v2 API has been removed
* Authentication required by default. In order to secure Sonarr from unauthorized users and to protect your private credentials Sonarr will now require authentication to be enabled when accessing the UI for the first time after installing or upgrading to v4

**Comment by ghost** [comment]
Looks like this is not actually a problem as I found that if you add "version: v4" into the sonarr section of the config file makes this work again.
